/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller2;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author estudiante
 */
public class Adivinar extends javax.swing.JFrame {

    /**
     * Creates new form Adivinar
     */
    public Adivinar() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRand = new javax.swing.JButton();
        txtRand = new javax.swing.JTextField();
        btnAdivinar = new javax.swing.JButton();
        txtAdivinar = new javax.swing.JTextField();
        lblIntentos = new javax.swing.JLabel();
        txtIntentos = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivinar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRand.setText("Random");
        btnRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandActionPerformed(evt);
            }
        });
        getContentPane().add(btnRand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtRand.setEditable(false);
        txtRand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 30, 20));

        btnAdivinar.setText("Adivinar");
        btnAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtAdivinar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtAdivinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 20));

        lblIntentos.setText("Intentos");
        getContentPane().add(lblIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        txtIntentos.setEditable(false);
        txtIntentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 20, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu ventana = new Menu();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandActionPerformed
        Random rand = new Random();
        int num = rand.nextInt(10)+1;
        if(num==0){
            btnRandActionPerformed(evt);
        }
        else{
            txtRand.setText(""+num);
            txtIntentos.setText(""+3);
        }
        
    }//GEN-LAST:event_btnRandActionPerformed

    private void btnAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinarActionPerformed
        int intentos = Integer.parseInt(txtIntentos.getText());
        int numero = Integer.parseInt(txtRand.getText());
        if(numero!=Integer.parseInt(txtAdivinar.getText()) && intentos == 1){
            JOptionPane.showMessageDialog(null, "Juego Perdido");
            Menu ventana = new Menu();
            ventana.setVisible(true);
            dispose();
        }
        else if(numero==Integer.parseInt(txtAdivinar.getText())){
            JOptionPane.showMessageDialog(null, "Juego Ganado");
            Menu ventana = new Menu();
            ventana.setVisible(true);
            dispose();
        }
        else if(numero!=Integer.parseInt(txtAdivinar.getText()) && intentos>1){
            intentos-=1;
            JOptionPane.showMessageDialog(null, "Numero erroneo, le quedan "+intentos+" intentos");
            txtIntentos.setText(""+intentos);
        }
    }//GEN-LAST:event_btnAdivinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adivinar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinar;
    private javax.swing.JButton btnRand;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JTextField txtAdivinar;
    private javax.swing.JTextField txtIntentos;
    private javax.swing.JTextField txtRand;
    // End of variables declaration//GEN-END:variables
}
